services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanguard_app
    depends_on:
      - psql
    restart: unless-stopped
    ports:
      - 9014:9014

  psql:
    image: postgres:15
    container_name: vanguard_psql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=vanguard
      - POSTGRES_PASSWORD=vanguard
      - POSTGRES_DB=vanguard
    volumes:
      - ./var/release/prod/psql:/var/lib/postgresql/data
    ports:
      - 9015:5432
